### ISSUE TITLE
新皮肤推荐（长期有效）

### ISSUE THREAD

**Issue by Vanessa219** [88250/solo#6]
请大家跟帖来推荐皮肤，我们会按点赞数进行参考并融入自己的风格后进行制作。当然，也欢迎大家参考 [Solo 皮肤开发指南](https://hacpai.com/article/1493814851007)自行开发。

* [ ]  icarus 参考：[hexo-theme-icarus](https://github.com/ppoffice/hexo-theme-icarus)
* [ ]  Anatole 参考：[CaiCai](http://anatole.cai-cai.me/)
* [ ]  meituan 参考：[美团技术团队](https://tech.meituan.com/)
* [ ]  even 参考：[hexo-theme-even](https://github.com/ahonn/hexo-theme-even)
* [ ]  matery 参考：[matery](https://github.com/blinkfox/hexo-theme-matery)
* [ ]  GitHub 参考：[小白妹妹写代码](https://sabrinaluo.github.io/tech/)
* [ ]  Material 参考：[typecho-theme-material](https://github.com/idawnlight/typecho-theme-material)
* [ ]  Affinity 参考：[Affinity](https://github.com/Showfom/Affinity)
* [ ]  Maybe 参考：[可能吧](https://kenengba.com/)
* [x]  [solo-nexmoe](https://github.com/JinJianh/solo-nexmoe) 参考： [Nexmoe](https://github.com/nexmoe/hexo-theme-nexmoe) by @JinJianh
* [x]  [Bubble](https://github.com/b3log/solo-skins/tree/master/Bubble) 参考：[JaJian](https://www.cnblogs.com/JaJian) ref [#12805](https://github.com/b3log/solo/issues/12805)
* [x]  [Casper](https://github.com/b3log/solo-skins/tree/master/Casper) 参考：[ghost 默认主题](https://github.com/TryGhost/Casper) ref [#12737](https://github.com/b3log/solo/issues/12737)
* [x]  [Pinghsu](https://github.com/b3log/solo-skins/tree/master/Pinghsu) 参考：[Pinghsu](https://github.com/chakhsu/pinghsu) ref [#12673](https://github.com/b3log/solo/issues/12673)
* [x]  [Jane](https://github.com/b3log/solo-skins/tree/master/Jane) 参考：[hexo-theme-jane](https://github.com/hejianxian/hexo-theme-jane) ref [#12584](https://github.com/b3log/solo/issues/12584)
* [x]  [nijigen](https://github.com/b3log/solo-skins/tree/master/nijigen) 部分参考：[hexo-theme-gal](https://github.com/ZEROKISEKI/hexo-theme-gal) ref [#12494](https://github.com/b3log/solo/issues/12494)
* [x]  [solo-skin-amaze](https://github.com/zjhch123/solo-skin-amaze) 参考： [typecho-theme-amaze ](https://github.com/spiritree/typecho-theme-amaze)by [@zjhch123](https://github.com/zjhch123)

未加入开发计划：

* [https://www.xiahuhu.cn/](https://www.xiahuhu.cn/)
* [https://github.com/DONGChuan/Yummy-Jekyll](https://github.com/DONGChuan/Yummy-Jekyll)
* [https://github.com/hongweipeng/GreenGrapes](https://github.com/hongweipeng/GreenGrapes)
* [https://www.jlpyyf.com/](https://www.jlpyyf.com/)
* [https://diygod.me/](https://diygod.me/) ～ Bubble + nijigen？
* [https://www.ihewro.com/](https://www.ihewro.com/)
